[{
    "backgroundLayoutID": 1,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 280.0
    }, {
        "width": 0.0
    }, {
        "width": 400.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 1,
        "rowspan": 3,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 0,
        "rowspan": 3,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1,
        "canCollapse": true
    }, {
        "id": 4,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1,
        "canCollapse": true
    }, {
        "id": 5,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1,
        "canCollapse": true
    }, {
        "id": 6,
        "row": 3,
        "column": 2,
        "rowspan": 1,
        "colspan": 1,
        "canCollapse": true
    },{
        "id": 7,
        "row": 3,
        "column": 0,
        "rowspan": 1,
        "colspan": 2
    }]
}, {
    "rows": [{
        "height": 0.0
    }],
    "cols": [{
        "width": 300.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
},{
    "rows": [{
        "height": 0.0
    },{
        "height": 0.0
    },{
        "height": 0.0
    },{
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 450.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 4,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 3,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 1,
        "rowspan": 2,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 2,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 200
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 200
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 2
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 3
    }, {
        "id": 2,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 1,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 4,
        "row": 0,
        "column": 2,
        "rowspan": 2,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 0,
        "column": 2,
        "rowspan": 2,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 3,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 2
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 2
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 2,
        "row": 0,
        "column": 2,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 3,
        "colspan": 2
    }, {
        "id": 2,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 2,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 0,
        "column": 1,
        "rowspan": 3,
        "colspan": 2
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 3
    }, {
        "id": 2,
        "row": 0,
        "column": 3,
        "rowspan": 1,
        "colspan": 3
    }, {
        "id": 3,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 4,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 5,
        "row": 1,
        "column": 4,
        "rowspan": 1,
        "colspan": 2
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 2
    }, {
        "id": 2,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 3,
        "row": 0,
        "column": 4,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 4,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 3
    }, {
        "id": 5,
        "row": 1,
        "column": 5,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 3,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 2,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 7,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 3,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 7,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 7,
        "row": 2,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 8,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 9,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 2,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 7,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 8,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 1,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 4,
        "colspan": 4
    }, {
        "id": 2,
        "row": 0,
        "column": 4,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 3,
        "row": 1,
        "column": 4,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 4,
        "row": 2,
        "column": 4,
        "rowspan": 1,
        "colspan": 2
    }, {
        "id": 5,
        "row": 3,
        "column": 4,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 3,
        "column": 5,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 1,
    "rows": [{
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 2,
    "rows": [{
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 1,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 2,
        "colspan": 2
    }, {
        "id": 2,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 2,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 1,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 3,
        "colspan": 2
    }, {
        "id": 2,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 2,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 3,
        "colspan": 2
    }, {
        "id": 3,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 2,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 2,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 2,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 3,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 3,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 2,
        "column": 0,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 7,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }]
}, {
    "backgroundLayoutID": 1,
    "rows": [{
        "height": 0.0
    }, {
        "height": 0.0
    }, {
        "height": 0.0
    }],
    "cols": [{
        "width": 0.0
    }, {
        "width": 0.0
    }, {
        "width": 0.0
    }],
    "layouts": [{
        "id": 1,
        "row": 0,
        "column": 0,
        "rowspan": 3,
        "colspan": 1
    }, {
        "id": 2,
        "row": 0,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 3,
        "row": 0,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 4,
        "row": 1,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 5,
        "row": 1,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 6,
        "row": 2,
        "column": 1,
        "rowspan": 1,
        "colspan": 1
    }, {
        "id": 7,
        "row": 2,
        "column": 2,
        "rowspan": 1,
        "colspan": 1
    }]
}]
